CREATE TABLE Cours (
    id UUID PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    body TEXT,
    videoUrl TEXT,
    matiereId UUID NOT NULL REFERENCES Matieres(id) ON DELETE CASCADE,
    userId UUID REFERENCES Users(id) ON DELETE SET NULL,
    isActive BOOLEAN DEFAULT TRUE,
    metadata JSONB,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);